### ISSUE TITLE
1.5.0 and up unusable

### ISSUE THREAD

**Issue by rmpel** [devjiwonchoi/po2mo#107]
Hi
Thank you for this tool, however, we seem unable to use any version from 1.5.0 on.

If we upgrade po2mo and keep our `po2mo.json`, we get error `MISSING_PO: No created, modified, or staged .po files found in the local Git repository at (path)`.
If we change `po2mo.json` to the new 'tasks' based format and specify with `--config ./po2mo.json`, we get error `TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///(path)/po2mo.json" needs an import assertion of type "json"
If we remove `po2mo.json`, we get error `MISSING_PO: No created, modified, or staged .po files found in the local Git repository at (path)`
There seems to be no possible method any more to just convert a po to a mo.

Either we're doing something wrong, but isn't documented clearly, or there's something wrong with the code that tries to parse the json file.

I've tried with Node versions 16, 18 and 20.

The only option for us at this time is downgrade to 1.4.0.

Can you assist? if so, what further information would you require from us?

Thanks.

**Comment by devjiwonchoi** [comment]
Hi, yes from v1.5 had a breaking change, and your approach:

> If we change po2mo.json to the new 'tasks' based format and specify with --config ./po2mo.json

seems correct, and it seems a bug from po2mo.

I'll fix it ASAP and release a new version with a migration guide from ~v1.4.

Also, it'd be great if you could share a minimum repro so I can confirm this fix can resolve your case.

**Comment by devjiwonchoi** [comment]
@rmpel  Also, from the latest version, po2mo converts the modified PO files only, reducing possible I/O operations. Please confirm that you actually need the config file!

**Comment by devjiwonchoi** [comment]
Could you try out v2.0.5? Thank you.

**Comment by rmpel** [comment]
Hi, thank you for your swift response.

We use the po2mo in a deployment pipeline, so the files would never be marked "changed".
Doesn't have to be a config file, for me, if we could do `cd languages ; po2mo *.po`, that would already solve it ;)

I will try 2.0.5 and let you know.

**Comment by rmpel** [comment]
❯ npx po2mo --config po2mo.json
Dirent { name: 'nl_NL.mo', [Symbol(type)]: 1 }
𝕏 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1172:7)
    at p ... {
  code: 'ERR_INVALID_ARG_TYPE'
}

this is after a beautification if the dist file. Since this file is 'compressed', hard to say where it maps in the source, but I managed to fix it with

``` javascript
async function p({
    input: e,
    recursive: t
}) {
    let o = [];
    for (let n of (await r.readdir(e, {
            withFileTypes: !0
        }))) {
        let e = i.join(n.path, n.name);
        if (n.isDirectory()) {
            if (!t) continue;
            let r = await p({
                input: e,
                recursive: !0
            });
            o.push(...r)
        }
        n.isFile() && n.name.endsWith(".po") && o.push(e)
    }
    return o
}
```
to
``` javascript
async function p({
    input: e,
    recursive: t
}) {
    let o = [];
    let dirpath=e;
    for (let n of (await r.readdir(e, {
            withFileTypes: !0
        }))) {
        let e = i.join(dirpath, n.name);
        if (n.isDirectory()) {
            if (!t) continue;
            let r = await p({
                input: e,
                recursive: !0
            });
            o.push(...r)
        }
        n.isFile() && n.name.endsWith(".po") && o.push(e)
    }
    return o
}
```

maybe the better fix would be
``` javascript
async function p({
    input: e,
    recursive: t
}) {
    let o = [];
    let rootdir=e;
    for (let n of (await r.readdir(e, {
            withFileTypes: !0
        }))) {
        let thisdir = n.path || rootdir
        let e = i.join(thisdir , n.name);
        if (n.isDirectory()) {
            if (!t) continue;
            let r = await p({
                input: e,
                recursive: !0
            });
            o.push(...r)
        }
        n.isFile() && n.name.endsWith(".po") && o.push(e)
    }
    return o
}
```
as I think that would preserve the ability to traverse deeper, but I don't have a set-up to test that.

my config file is
``` json
{
  "tasks": [
    {
      "input": "./languages/",
      "output": "./languages/"
    }
  ]
}
```

**Comment by devjiwonchoi** [comment]
Thank you for sharing your debugging, I guess it's better to not compress on dist from now on.

Could you create a minimum reproduction so I can make sure I can resolve your issue?

Maybe a temporary github repo or at least a file tree would be great!

**Comment by rmpel** [comment]
Sure thing; https://github.com/rmpel/po2mo-issue-test

**Comment by devjiwonchoi** [comment]
<img width="595" alt="Screenshot 2024-04-25 at 10 33 05 PM" src="https://github.com/devjiwonchoi/po2mo/assets/120007119/54fa15d2-3c6d-42d5-ba8d-8cc8ca88ac36">

<img width="481" alt="Screenshot 2024-04-25 at 11 04 59 PM" src="https://github.com/devjiwonchoi/po2mo/assets/120007119/532ada92-36bb-4420-b649-9e1c2380f921">

Hmm.. works fine on mine. What version is your npm?

**Comment by devjiwonchoi** [comment]
I'm assuming its caused by `Dirent.path`:

```
(property) Dirent.path: string
The base path that this fs.Dirent object refers to.

@since — v20.1.0
```

Node.js version 18.17.1 and up should work fine, I'll add engines version for it, thank you opening up this issue!

![Screenshot 2024-05-10 at 1 57 18 AM](https://github.com/devjiwonchoi/po2mo/assets/120007119/14246b12-7cbb-467c-a67f-0ecb0be68033)
